export type SvgImages =
  'background_dashboard'
  | 'bosque_logo'
  | 'bosque_logo_white'
  | 'delivery'
  | 'list_logo'
  | 'map_logo'
  | 'message_alert'
  | 'profile'
  | 'profile_admin'
  | 'profile_lots'
  | 'profile_medical_center'
  | 'profile_nurse'
  | 'select_user'
  | 'send_logo'
  | 'system_settings'
  | 'system_user'
  | 'vaccine'
  | 'medical_center'
  | 'vaccine_lots';
